version: '3.3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - ${API_PORT:-8000}:${API_PORT:-8000}
    networks:
      - polarisai-services-nw
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD', 'curl', '--silent', '--fail', '-X', 'GET', 'http://localhost:${API_PORT}/' ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 2
    env_file:
      - ${ENV_FILE_PATH}

  mysql:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - polarisai-services-nw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: "mysql"
      KC_DB_URL: "jdbc:mysql://mysql:3306/keycloak_db"
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_SCRIPT_UPLOAD: "true"
    restart: always
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/import:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    networks:
      - polarisai-services-nw
    depends_on:
      mysql:
        condition: service_healthy
    command: 
      - start-dev
      - --import-realm
      - --verbose

volumes:
  mysql_data:
    name: polarisai_mysql_data
  keycloak_data:
    name: polarisai_keycloak_data

networks:
  polarisai-services-nw:
    name: polarisai-services-nw
    external: true