FROM python:3.10-slim

RUN apt-get update && apt-get install curl -y

WORKDIR /api

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ARG API_PORT
ENV API_PORT=${API_PORT}

ENTRYPOINT uvicorn server:app --host "0.0.0.0" --port "${API_PORT}"

