FROM python:3.10-slim

RUN apt-get update && apt-get install curl -y

WORKDIR /api

COPY app/requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT uvicorn app.main:app --host "0.0.0.0" --port "${API_PORT}"
